### ISSUE TITLE
Error while executing MSSQL db scripts

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10201]
### Description:
Following syntax errors are displayed while executing _dbscripts\apimgt\mssql_ table creation script.
```
Msg 102, Level 15, State 1, Line 2286
Incorrect syntax near 'ENGINE'.
Msg 102, Level 15, State 1, Line 2297
Incorrect syntax near 'ENGINE'.
Msg 102, Level 15, State 1, Line 2311
Incorrect syntax near 'ENGINE'.
Msg 102, Level 15, State 1, Line 2325
Incorrect syntax near 'ENGINE'.
```

![Capture](https://user-images.githubusercontent.com/32265029/110433724-b021f600-8065-11eb-9580-d1b418d563a3.JPG)

### Steps to reproduce:

1. Install mssql server 2019
2. Download wso2am-4.0.0-alpha
3. Create db apim_db
4. Go to _wso2am-4.0.0-alpha\dbscripts\apimgt_
5. Open and copy mssql script
6. Paste and execute mssql script

### Affected Product Version:
4.0.0-alpha

### Environment details (with versions):
- OS: Windows 10
- DB :  MSSQL server 2019

#### Suggested Labels:
API-M 4.0.0

**Comment by CrowleyRajapakse** [comment]
This is fixed in the latest

**Comment by TheRasanjana** [comment]
I've got the latest build and still getting following error.
```
Msg 1785, Level 16, State 0, Line 1736
Introducing FOREIGN KEY constraint 'FK__AM_API_CO__PAREN__090A5324' on table 'AM_API_COMMENTS' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Msg 1750, Level 16, State 1, Line 1736
Could not create constraint or index. See previous errors.
```

**Comment by malinthaprasan** [comment]
@TheRasanjana seems like a fix is merged to the lastest. Can you verify this in the latest jenkins build?

**Comment by TheRasanjana** [comment]
This is fixed in the latest.
