### ISSUE TITLE
Issues in executing mysql scripts of AM table.

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/product-apim#10337]
### Description:

In the latest stable pack when executing the API management MySQL DB scripts (`$APIM_HOME/dbscripts/mysql.sql`), errors encountered.

`ERROR 1067 (42000) at line 1512 in file: 'wso2am-4.0.0-SNAPSHOT/dbscripts/apimgt/mysql.sql': Invalid default value for 'UPDATED_TIME'`.

This is encountered due to the `UPDATED_TIME TIMESTAMP` column of the `AM_API_COMMENTS` table.

When changing `UPDATED_TIME TIMESTAMP DEFAULT NULL`  to  `UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP` in the scripts this error get resolved.

### Steps to reproduce:

Run the MySQL scripts in` $APIM_HOME/dbscripts/apimgt/mysql.sql`

### Affected Product Version:

APIM 4.0.0

### Environment details (with versions):
- OS: Ubuntu 18.04
- Mysql : mysql Ver 14.14 Distrib 5.7.33

**Comment by tmkasun** [comment]
This is already fixed in master hence closing the issue
https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.core.feature/src/main/resources/sql/mysql.sql#L1511

**Comment by mushthaq33** [comment]
<img width="903" alt="Screenshot 2021-03-18 at 10 55 01" src="https://user-images.githubusercontent.com/15009816/111578190-a58bfd00-87d9-11eb-8907-6729267c732d.png">
Seems the issue still persists.

**Comment by thisaltennakoon** [comment]
Fixed this in this [PR](https://github.com/wso2/carbon-apimgt/pull/10021)
