### ISSUE TITLE
Faulty response received in JMS dual channel scenairo when JMS service returns content-type as text/xml

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#4807]
**Description:**
In JMS dual channel scenario, when the JMS service returns the response within SOAP envelope  and content-type as text/xml, faulty response is received. For example if back-end sends response as:
```
<?xml version='1.0' encoding='utf-8'?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
	<env:Header>
      		<t:Transaction xmlns:t="http://example.org/2001/06/tx" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:int" env:encodingStyle="http://www.w3.org/2001/06/soap-encoding" env:mustUnderstand="1">5</t:Transaction>
   	</env:Header>
	<env:Body>
      		<m:GetLastTradePriceResponse xmlns:m="http://example.org/2001/06/quotes" env:encodingStyle="http://www.w3.org/2001/06/soap-encoding">
         		<Price>34.5</Price>
      		</m:GetLastTradePriceResponse>
   	</env:Body>
</env:Envelope>
```
Response sent out from APIM is :
```
<m:GetLastTradePriceResponse xmlns:m="http://example.org/2001/06/quotes" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" env:encodingStyle="http://www.w3.org/2001/06/soap-encoding">
         <Price>34.5</Price>
</m:GetLastTradePriceResponse>
```

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.6.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by npamudika** [comment]
Fixed with above PR

**Comment by dushaniw** [comment]
Reopening since the issue still exists when selecting the message formatter.
