### ISSUE TITLE
APIM 3.0 - System error when enabling message tracing configuration

### ISSUE THREAD

**Issue by WathsalaKoralege** [wso2/product-apim#6831]
**Description**
When trying to enable message tracing via carbon console it shows the below message.
![image](https://user-images.githubusercontent.com/44961438/68878209-50dffa00-072d-11ea-8219-9a7af9889fe3.png)

Related stack trace:
```
ERROR - RPCInOnlyMessageReceiver Exception occurred while trying to invoke service method configureEventing
java.lang.NullPointerException: null
at org.wso2.carbon.analytics.message.tracer.handler.conf.RegistryPersistenceManager.updateConfigurationProperty(RegistryPersistenceManager.java:84) ~[org.wso2.carbon.analytics.message.tracer.handler_1.4.2.jar:?]
at org.wso2.carbon.analytics.message.tracer.handler.conf.RegistryPersistenceManager.update(RegistryPersistenceManager.java:110) ~[org.wso2.carbon.analytics.message.tracer.handler_1.4.2.jar:?]
at org.wso2.carbon.analytics.message.tracer.handler.services.MessageTracerAdmin.configureEventing(MessageTracerAdmin.java:34) ~[org.wso2.carbon.analytics.message.tracer.handler_1.4.2.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212) ~[axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.rpc.receivers.RPCInOnlyMessageReceiver.invokeBusinessLogic(RPCInOnlyMessageReceiver.java:66) [axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110) [axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:170) [axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.transport.local.LocalTransportReceiver.processMessage(LocalTransportReceiver.java:82) [axis2_1.6.1.wso2v38.jar:?]
at org.wso2.carbon.core.transports.local.CarbonLocalTransportSender.finalizeSendWithToAddress(CarbonLocalTransportSender.java:45) [org.wso2.carbon.core_4.5.1.jar:?]
at org.apache.axis2.transport.local.LocalTransportSender.invoke(LocalTransportSender.java:77) [axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442) [axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:442) [axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228) [axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) [axis2_1.6.1.wso2v38.jar:?]
at org.wso2.carbon.analytics.message.tracer.handler.stub.MessageTracerAdminStub.configureEventing(MessageTracerAdminStub.java:1008) [org.wso2.carbon.analytics.message.tracer.handler.stub_1.4.2.jar:?]
at org.wso2.carbon.analytics.message.tracer.handler.ui.MessageTracerHandlerAdminClient.setEventingConfigData(MessageTracerHandlerAdminClient.java:55) [org.wso2.carbon.analytics.message.tracer.handler.ui_1.4.2.jar:?]
at org.apache.jsp.bampubsvcstat.configure_005fmessage_005ftracing_jsp._jspService(configure_005fmessage_005ftracing_jsp.java:239) [hc_1301080911/:?]
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [tomcat_9.0.22.wso2v1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) [tomcat_9.0.22.wso2v1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207) [org.wso2.carbon.ui_4.5.1.jar:?]
at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80) [org.wso2.carbon.ui_4.5.1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516) [tomcat_9.0.22.wso2v1.jar:?]
at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:37) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.include(ContextPathServletAdaptor.java:369) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:900) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:496) [tomcat_9.0.22.wso2v1.jar:?]
at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
at org.apache.tiles.jsp.context.JspUtil.doInclude(JspUtil.java:87) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.context.JspTilesRequestContext.include(JspTilesRequestContext.java:88) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.context.JspTilesRequestContext.dispatch(JspTilesRequestContext.java:82) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:465) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:140) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:117) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.taglib.RenderTagSupport.execute(RenderTagSupport.java:171) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.taglib.RoleSecurityTagSupport.doEndTag(RoleSecurityTagSupport.java:75) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.taglib.ContainerTagSupport.doEndTag(ContainerTagSupport.java:80) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.jsp.admin.layout.template_jsp._jspx_meth_tiles_005finsertAttribute_005f7(template_jsp.java:780) [hc_1301080911/:?]
at org.apache.jsp.admin.layout.template_jsp._jspService(template_jsp.java:443) [hc_1301080911/:?]
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [tomcat_9.0.22.wso2v1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) [tomcat_9.0.22.wso2v1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207) [org.wso2.carbon.ui_4.5.1.jar:?]
at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80) [org.wso2.carbon.ui_4.5.1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) [tomcat_9.0.22.wso2v1.jar:?]
at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.forward(RequestDispatcherAdaptor.java:30) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.forward(ContextPathServletAdaptor.java:362) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
at org.apache.tiles.servlet.context.ServletTilesRequestContext.forward(ServletTilesRequestContext.java:198) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.servlet.context.ServletTilesRequestContext.dispatch(ServletTilesRequestContext.java:185) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:419) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:370) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.wso2.carbon.ui.action.ActionHelper.render(ActionHelper.java:52) [org.wso2.carbon.ui_4.5.1.jar:?]
at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:101) [org.wso2.carbon.ui_4.5.1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88) [csrfguard_3.1.0.wso2v3.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.6.jar:?]
at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.6.jar:?]
at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.6.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[2019-11-14 09:45:46,749] ERROR - MessageTracerHandlerAdminClient Cannot set eventing configuration. Backend server may be unavailable.
org.apache.axis2.AxisFault: unknown
at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531) ~[axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91) ~[axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:457) ~[axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228) ~[axis2_1.6.1.wso2v38.jar:?]
at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) ~[axis2_1.6.1.wso2v38.jar:?]
at org.wso2.carbon.analytics.message.tracer.handler.stub.MessageTracerAdminStub.configureEventing(MessageTracerAdminStub.java:1008) ~[org.wso2.carbon.analytics.message.tracer.handler.stub_1.4.2.jar:?]
at org.wso2.carbon.analytics.message.tracer.handler.ui.MessageTracerHandlerAdminClient.setEventingConfigData(MessageTracerHandlerAdminClient.java:55) [org.wso2.carbon.analytics.message.tracer.handler.ui_1.4.2.jar:?]
at org.apache.jsp.bampubsvcstat.configure_005fmessage_005ftracing_jsp._jspService(configure_005fmessage_005ftracing_jsp.java:239) [hc_1301080911/:?]
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [tomcat_9.0.22.wso2v1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) [tomcat_9.0.22.wso2v1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207) [org.wso2.carbon.ui_4.5.1.jar:?]
at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80) [org.wso2.carbon.ui_4.5.1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:580) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:516) [tomcat_9.0.22.wso2v1.jar:?]
at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:37) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.include(ContextPathServletAdaptor.java:369) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:900) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:496) [tomcat_9.0.22.wso2v1.jar:?]
at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
at org.apache.tiles.jsp.context.JspUtil.doInclude(JspUtil.java:87) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.context.JspTilesRequestContext.include(JspTilesRequestContext.java:88) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.context.JspTilesRequestContext.dispatch(JspTilesRequestContext.java:82) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:465) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:140) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:117) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.taglib.RenderTagSupport.execute(RenderTagSupport.java:171) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.taglib.RoleSecurityTagSupport.doEndTag(RoleSecurityTagSupport.java:75) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.jsp.taglib.ContainerTagSupport.doEndTag(ContainerTagSupport.java:80) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.jsp.admin.layout.template_jsp._jspx_meth_tiles_005finsertAttribute_005f7(template_jsp.java:780) [hc_1301080911/:?]
at org.apache.jsp.admin.layout.template_jsp._jspService(template_jsp.java:443) [hc_1301080911/:?]
at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [tomcat_9.0.22.wso2v1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329) [tomcat_9.0.22.wso2v1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:207) [org.wso2.carbon.ui_4.5.1.jar:?]
at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80) [org.wso2.carbon.ui_4.5.1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) [tomcat_9.0.22.wso2v1.jar:?]
at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.forward(RequestDispatcherAdaptor.java:30) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.forward(ContextPathServletAdaptor.java:362) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
at org.apache.tiles.servlet.context.ServletTilesRequestContext.forward(ServletTilesRequestContext.java:198) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.servlet.context.ServletTilesRequestContext.dispatch(ServletTilesRequestContext.java:185) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:419) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:370) [tiles-jsp_2.0.5.wso2v1.jar:?]
at org.wso2.carbon.ui.action.ActionHelper.render(ActionHelper.java:52) [org.wso2.carbon.ui_4.5.1.jar:?]
at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:101) [org.wso2.carbon.ui_4.5.1.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37) [org.eclipse.equinox.http.helper_1.1.0.wso2v1.jar:?]
at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68) [org.eclipse.equinox.http.servlet_1.1.400.v20130418-1354.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:88) [csrfguard_3.1.0.wso2v3.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.6.jar:?]
at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.6.jar:?]
at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.6.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]
at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Version**
APIM 3.0

**Comment by dushaniw** [comment]
same issue https://github.com/wso2/product-apim/issues/6753

**Comment by tharindu1st** [comment]
tagging https://github.com/wso2/product-apim/issues/7281

**Comment by Krishanx92** [comment]
This is fixed now.

**Comment by sharathrsher** [comment]
The problem still exists. Its on APIM v3.0.0

[2020-03-12 05:11:07,765] ERROR {org.wso2.carbon.analytics.message.tracer.handler.ui.MessageTracerHandlerAdminClient} - Cannot set eventing configuration. Backend server may be unavailable. org.apache.axis2.AxisFault: unknown
        at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
        at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:457)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:228)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
        at org.wso2.carbon.analytics.message.tracer.handler.stub.MessageTracerAdminStub.configureEventing(MessageTracerAdminStub.java:1008)
        at org.wso2.carbon.analytics.message.tracer.handler.ui.MessageTracerHandlerAdminClient.setEventingConfigData(MessageTracerHandlerAdminClient.java:55)
