### ISSUE TITLE
SecureWebSocketInboundEndpoint.xml.j2 is not deleted when running profile optimizer for traffic-manager

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#8039]
### Description:
When we run the profileSetup.sh for traffic-manager profile, the SecureWebSocketInboundEndpoint.xml.j2 from /repository/conf/templates is not deleted. Hence, when we start the server after the optimization, the SecureWebSocketInboundEndpoint.xml is created again in synapse-configs/default/inbound-endpoints directory. So the second server startup fails, as there is a record in resource/conf/.metadata/metadata_config.properties for the previous SecureWebSocketInboundEndpoint.xml.

```
repository/deployment/server/synapse-configs/default/inbound-endpoints/SecureWebSocketInboundEndpoint.xml=7c01796590d59b8be997dec801c4381b
```

So in second server startup we are getting the following error,
```
JAVA_HOME environment variable is set to /usr/lib/jvm/jdk1.8.0_231/
CARBON_HOME environment variable is set to /home/dushaniw/.wum3/products/wso2am/3.1.0/full/test2/wso2am-3.1.0
Using Java memory options: -Xms256m -Xmx1024m
[2020-05-12 17:42:26,457]  SEVERE {org.wso2.carbon.server.Main handleConfiguration} - Error while performing configuration changes 
org.wso2.config.mapper.ConfigParserException: Error while reading metadata
	at org.wso2.config.mapper.MetaDataParser.readLastModifiedValue(MetaDataParser.java:76)
	at org.wso2.config.mapper.MetaDataParser.getChangedFiles(MetaDataParser.java:156)
	at org.wso2.config.mapper.ConfigParser.parse(ConfigParser.java:103)
	at org.wso2.carbon.server.Main.handleConfiguration(Main.java:231)
	at org.wso2.carbon.server.Main.main(Main.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.carbon.bootstrap.Bootstrap.loadClass(Bootstrap.java:70)
	at org.wso2.carbon.bootstrap.Bootstrap.main(Bootstrap.java:51)
Caused by: java.io.FileNotFoundException: /home/dushaniw/.wum3/products/wso2am/3.1.0/full/test2/wso2am-3.1.0/repository/deployment/server/synapse-configs/default/inbound-endpoints/SecureWebSocketInboundEndpoint.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.wso2.config.mapper.MetaDataParser.getMetadata(MetaDataParser.java:97)
	at org.wso2.config.mapper.MetaDataParser.readLastModifiedValue(MetaDataParser.java:74)
	... 10 more
```
 

### Steps to reproduce:
1. Run the profile optimizer for traffic-manager profile
2. Start the server in  traffic-manager profile.
3. Shutdown the server and restart again.

### Affected Product Version:
3.0 and 3.1

### Environment details (with versions):
- OS: Ubuntu 19.04

**Comment by msm1992** [comment]
This issue is fixed in APIM 3.0.0 and 3.1.0 latest WUM. Issue is fixed in master branch with https://github.com/wso2/product-apim/commit/045cedaad6d74024cd57a403adf40abc1050306f, hence resolving this issue.

**Comment by pouyan021** [comment]
We still face this issue on APIM 3.2.0 version, I think this problem still persists
I run the server according to docs using this command:

`sh wso2server.sh --optimize -Dprofile=traffic-manager --skipConfigOptimization`

Yet I still get the very same error.
