### ISSUE TITLE
[APIM-3.2.0] Publisher portal theme configurations made on userThemes.js are not reflected

### ISSUE THREAD

**Issue by athiththan11** [wso2/product-apim#9324]
### Description:

The theme changes made to the `userThemes.js` of the Publisher node are getting reflected in the Publisher UI.

### Steps to reproduce:

1. Run an APIM 3.2 pack
2. Go to `<apim>/repository/deployment/server/jaggeryapps/publisher/site/public/conf` directory
3. Open and edit the `userThemes.js` (add a logo)
4. Save and refresh the UI

### Affected Product Version:

* API Manager v3.2.0

**Comment by tmkasun** [comment]
fixed in https://github.com/wso2/carbon-apimgt/pull/9297

**Comment by Hervinho** [comment]
This is still not working properly. I have v3.2.0 and I tried to change the background palette as follows
`palette: {
                    background: {
                        appBar: '#f2f2f2', 
                        appBarSelected: '#85c441',
                        leftMenu: '#f2f2f2', 
                        leftMenuActive: '#f2f2f2',
                        drawer: '#1a1f2f',
                        activeMenuItem: '#008ea9',
                    },
                },
`

**Comment by Ritesh45C** [comment]
This is still not working at all in latest version 3.2.0. No changes are reflecting in the UI.

**Comment by tmkasun** [comment]
@Ritesh45C ,

You have to take a WUM update to get this fix, or If you build the distribution from the master branch , you could get this fix. This will be available in the upcoming API Manager 4.0.0 release.

**Comment by ernsheong** [comment]
I patched ProtectedApp.jsx and still userThemes.js changes did not seem to pick up.
